### ISSUE TITLE
Consider object getter/setter API

### ISSUE THREAD

**Issue by davidmarkclements** [thlorenz/v8-flags#3]
Just pushed this: 

https://www.npmjs.com/package/v8-flags-object-proxy

Happy for you to steal it and will deprecate module if you choose to use it

**Comment by thlorenz** [comment]
I've seen that and don't see a huge gain there.
Could you explain to me what I'm missing? How is `foo(x)` so much harder than `foo = x`?

**Comment by davidmarkclements** [comment]
The main benefit from my perspective is functional object composition. If we treat the flags as a key value store instead of a command list then it's easier to mixin other data sources (eg cli options, cfg files, post requests) when that data is also represented as an object. Essentially for me it boils down to this: `_.assign(flags, opts)`  as opposed to traversing the object and conditionally calling various methods based on the presence of properties.

**Comment by thlorenz** [comment]
While I get the convenience you're after that can be easily solved and isn't worth changing the API especially considering setters have more overhead than just a function call.

Here's an example:

``` js
Object.keys(config).forEach(assign);
function assign(k) {
   var val = config[k];
   if (typeof flags[k] === 'function') flags[k](val);
   else \\ warn
}
```

So just put that in your code somewhere and use that (or use your version of the v8-flags).

**Comment by davidmarkclements** [comment]
fair enough :)

On Fri, Apr 24, 2015 at 5:34 PM, Thorsten Lorenz notifications@github.com
wrote:

> While I get the convenience you're after that can be easily solved and
> isn't worth changing the API especially considering setters have more
> overhead than just a function call.
> 
> Here's an example:
> 
> Object.keys(config).forEach(assign);function assign(k) {
>    var val = config[k];
>    flags[k](val);
> }
> 
> So just put that in your code somewhere and use that (or use your version
> of the v8-flags).
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/thlorenz/v8-flags/issues/3#issuecomment-95986677.

## 

David Mark Clements Ltd is a company registered in Northern Ireland.
Registered number: NI617728. Registered office: Unit 22a, Pennybridge
Industrial Estate,
Ballymena, Antrim, BT42 3HB
